import logging
import json
import pandas as pd
import numpy as np
from pathlib import Path
from tqdm import tqdm
from PIL import Image
import torch

from thesis_pipeline.config_manager import ConfigManager
from thesis_pipeline.components.evaluation.baselines import TeleaInpainter, NavierStokesInpainter, VanillaSDInpainter
from thesis_pipeline.components.evaluation.metrics import ThesisMetrics

class BaselinesStage:
    """Stage 04 — Baseline Benchmarking (3×3 Matrix).

    Evaluates classical and generic-AI baselines on the **test split** using
    the **same masks** generated by Stage 10.  This ensures an apples-to-apples
    comparison with the fine-tuned model evaluation in Stage 13.
    """

    def __init__(self, config_manager: ConfigManager):
        self.config_manager = config_manager
        self.config = config_manager.config
        self.logger = logging.getLogger(__name__)

        self.output_dir = self.config_manager.get_stage_artifact_dir("S05")
        self.output_dir.mkdir(parents=True, exist_ok=True)
        
        # Use the inpainting test split as input — same data Stage 13 uses.
        self.test_gt_dir = Path(self.config.paths.data.inpainting) / "test" / "ground_truth"
        self.test_mask_dir = Path(self.config.paths.data.inpainting) / "test" / "masks"
        
        # Captions from Stage 06 / S03
        self.caption_dir = self.config_manager.get_stage_artifact_dir("S07")
        
    def load_captions(self):
        raw_file = self.caption_dir / "captions_raw.json"
        enriched_file = self.caption_dir / "captions_enriched.json"
        
        raw = {}
        if raw_file.exists():
            with open(raw_file, 'r') as f: raw = json.load(f)
            
        enriched = {}
        if enriched_file.exists():
            with open(enriched_file, 'r') as f: enriched = json.load(f)
            
        return raw, enriched

    def run(self):
        self.logger.info("="*20 + " STAGE 04: Baseline Benchmarking (3x3 Matrix) " + "="*20)
        
        if not self.test_gt_dir.exists():
            self.logger.warning(f"Test ground-truth not found at {self.test_gt_dir}. "
                                "Run Stages 09-10 first. Skipping baselines.")
            return

        # --- Gather test images and their matching masks (by stem) ---
        gt_files = sorted(self.test_gt_dir.glob("*.png"))
        if not gt_files:
            self.logger.warning("No PNG images found in test ground-truth. Skipping.")
            return

        sample_size = self.config.get("model_evaluation", {}).get("num_samples_to_evaluate", 20)
        gt_files = gt_files[:sample_size]

        # Build {stem → mask_path} lookup
        available_masks = {p.stem: p for p in self.test_mask_dir.glob("*.png")}

        paired = []
        for gt_path in gt_files:
            mask_path = available_masks.get(gt_path.stem)
            if mask_path is None:
                self.logger.error(
                    f"No mask found for test image '{gt_path.name}' — skipping this image. "
                    f"Ensure Stage 10 generated masks for the test split."
                )
                continue
            paired.append((gt_path, mask_path))

        if not paired:
            self.logger.error("Zero valid image-mask pairs found. Cannot run baselines.")
            return

        self.logger.info(f"Evaluating baselines on {len(paired)} image-mask pairs.")

        raw_caps, enriched_caps = self.load_captions()
        metrics_calc = ThesisMetrics()
        
        num_steps = self.config.get("model_evaluation", {}).get("num_inference_steps", 50)
        eval_seed = self.config.get("global_params", {}).get("random_state", 42)
        
        models = {
            "Telea": TeleaInpainter(),
            "NavierStokes": NavierStokesInpainter(),
            "VanillaSD": VanillaSDInpainter(num_inference_steps=num_steps, seed=eval_seed)
        }
        
        text_modes = ["Unconditional", "Raw", "Enriched"]
        all_results = []
        
        for model_name, model in models.items():
            self.logger.info(f"Processing Model: {model_name}")
            
            for mode in text_modes:
                # Classical models don't care about text mode, only run once
                if model_name in ["Telea", "NavierStokes"] and mode != "Unconditional":
                    continue
                
                self.logger.info(f"  Mode: {mode}")
                mode_dir = self.output_dir / model_name / mode
                mode_dir.mkdir(parents=True, exist_ok=True)
                
                for gt_path, mask_path in tqdm(paired, desc=f"{model_name}-{mode}"):
                    try:
                        img = Image.open(gt_path).convert("RGB").resize((512, 512))
                        mask = Image.open(mask_path).convert("L").resize((512, 512), Image.NEAREST)
                        
                        # Select Prompt — empty string for unconditional (no hardcoded fallback)
                        prompt = ""
                        if mode == "Raw":
                            prompt = raw_caps.get(gt_path.name, "")
                        elif mode == "Enriched":
                            prompt = enriched_caps.get(gt_path.name, "")
                        
                        if mode != "Unconditional" and not prompt:
                            self.logger.debug(
                                f"No caption for {gt_path.name} in mode={mode}; using empty prompt."
                            )
                            
                        # Inpaint
                        res = model.inpaint(img, mask, prompt=prompt)
                        res.save(mode_dir / f"{gt_path.stem}.png")
                        
                        # Calculate Metrics — both full-image and masked-region
                        gt_np = np.array(img)
                        pred_np = np.array(res)
                        mask_np = np.array(mask)
                        
                        scores = {
                            "filename": gt_path.name,
                            "model": model_name,
                            "mode": mode,
                            "mask_coverage": float(np.sum(mask_np > 0) / mask_np.size),
                            # Full-image metrics (for reference)
                            "psnr_full": metrics_calc.calculate_psnr(gt_np, pred_np),
                            "ssim_full": metrics_calc.calculate_ssim(gt_np, pred_np),
                            "lpips_full": metrics_calc.calculate_lpips(gt_np, pred_np),
                            "color_full": metrics_calc.calculate_color_fidelity(gt_np, pred_np),
                            "pattern_full": metrics_calc.calculate_pattern_preservation(gt_np, pred_np),
                            # Masked-region metrics (primary — evaluates inpainting quality)
                            "psnr": metrics_calc.calculate_psnr(gt_np, pred_np, mask=mask_np),
                            "ssim": metrics_calc.calculate_ssim(gt_np, pred_np, mask=mask_np),
                            "lpips": metrics_calc.calculate_lpips(gt_np, pred_np, mask=mask_np),
                            "color": metrics_calc.calculate_color_fidelity(gt_np, pred_np, mask=mask_np),
                            "pattern": metrics_calc.calculate_pattern_preservation(gt_np, pred_np, mask=mask_np),
                        }
                        all_results.append(scores)
                        
                    except Exception as e:
                        self.logger.error(f"Error processing {gt_path.name} with {model_name}-{mode}: {e}")

        # Save Results
        df = pd.DataFrame(all_results)
        df.to_csv(self.output_dir / "baseline_detailed_results.csv", index=False)
        
        summary = df.groupby(["model", "mode"]).mean(numeric_only=True)
        summary.to_csv(self.output_dir / "baseline_summary.csv")
        
        self.logger.info("Summary Stats:\n" + str(summary))
        self.logger.info("="*20 + " STAGE 04 COMPLETED " + "="*20 + "\n")

if __name__ == '__main__':
    from thesis_pipeline.config_manager import ConfigManager
    cm = ConfigManager()
    stage = BaselinesStage(cm)
    stage.run()
